language: php
php:
  # aliased to a recent 5.2.x version
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  
env:
  - DB=mysql
  
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi
  
# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_$DB.xml --coverage-text
